name: data730-lecture
channels:
  - conda-forge
  - chuckpr
dependencies:
  - python=3.9
  - jupyterlab-lsp
  - r-base
  - r-irkernel
  - r-tidymodels
  - r-tidyverse
  - r-vip
  - r-ranger
  - r-islr2
  - r-moderndive
  - r-rpart
  - r-rpart.plot
  - r-ranger
  - r-palmerpenguins
  - scikit-learn
  - plotnine
  - statsmodels
  - altair
  - ipykernel
  - pip:
      - palmerpenguins
      - drawdata
